require 'squib'
load 'deck.rb'

task default: [:deck]

task :abilities, [:cardFile,:outputFile] do |task, args|
    args.with_defaults(cardFile: "cardfiles/abilities.csv", outputFile: "abilities.pdf")
    buildAbilities(args[:cardFile],args[:outputFile])
end

task :equipment, [:cardFile,:outputFile] do |task, args|
    args.with_defaults(cardFile: "cardfiles/equipment.csv", outputFile: "equipment.pdf")
    buildEquipment(args[:cardFile],args[:outputFile])
end

task :monsters, [:cardFile,:outputFile] do |task, args|
    args.with_defaults(cardFile: "cardfiles/monsters.csv", outputFile: "monsters.pdf")
    buildMonsters(args[:cardFile],args[:outputFile])
end

task :characters, [:outputFile] do |task, args|
    args.with_defaults(outputFile: "characters.pdf")
    buildCharacters(args[:outputFile])
end

task :environments, [:outputFile] do |task, args|
    args.with_defaults(outputFile: "environments.pdf")
    buildEnvironments(args[:outputFile])
end

task :deck => [:abilities,:equipment,:monsters,:characters,:environments] do
end

task :noOp do
end